### ISSUE TITLE
missing .Rmd

### ISSUE THREAD

**Issue by jvcasillas** [julioclo/QPData#1]
@julioclo I don't see any .Rmd file. Can you add it?

**Comment by julioclo** [comment]
Me daba error cuando intentaba generar archivos .Rmd. Voy a intentarlo de nuevo.

**Comment by julioclo** [comment]
@jvcasillas Me daba error cuando intentaba generar archivos .Rmd. Voy a intentarlo de nuevo.

**Comment by julioclo** [comment]
@jvcasillas Acabo de añadirlos. Ojalá lo haya hecho bien y puedas verlos. ¿Tal vez debería copiar los resultados de la consola en el .Rmd como #comentario para que los puedas ver? Estoy más perdío que el barco del arroz.

**Comment by jvcasillas** [comment]
@julioclo voy a echarle un vistazo ahora. La primera cosa que veo es que has puesto todo el código R en el archivo .Rmd sin incluir chunks. Recuerda de la clase del martes que tienes que poner el código dentro de un R chunk, si no R piensa que es texto normal. Un ejemplo...

    ```{r}
    2 + 2
    ```

**Comment by jvcasillas** [comment]
@julioclo check the pull request. It should work for you now.
